alias disk="df -kl | egrep '/$'"
alias ed='ed -p "# "'
alias em='emacs -mm '
alias eq="emacs -Q -nw --eval \"(setq frame-background-mode 'light)\""
alias en="emacs -nw"
alias gs="git status --porcelain -b"
alias httpd='npx http-server'
alias apple='eog ~/img/apple &'
alias view=evince
alias commit='git commit -am'
